require_relative '../swift_template_generator'

module Redbreast
    module TemplateGenerator
        module Test
            class Swift < TemplateGenerator::Swift
                include ERB::Util

                def template()
<<-TEMPLATE

import UIKit
@testable import <%= bundle[:testableImport] %>

//THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
class <%= File.basename(bundle[:outputTestPath], ".*") %>: XCTestCase {

    func testIfImagesArePresent() {
        <%- image_names.each do |name| -%>
        _ = UIImage.<%= clean_variable_name(name) %>
        <%- end -%>    
    }

}

TEMPLATE
                end
            end
        end
    end
end