require 'redbreast/template_generators/swiftui_template_generator'

module Redbreast
  module TemplateGenerator
    module ImageTest
      # Used for creating image tests in swift.
      class SwiftUI < TemplateGenerator::SwiftUI
        include ERB::Util
        def template
<<~TEMPLATE
  import SwiftUI
  import XCTest
  @testable import <%= bundle[:testableImport] %>

  // THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
  class <%= File.basename(bundle[:outputTestPathImages], ".*") %>: XCTestCase {

      func testIfImagesArePresent() {
    <%= create_swift_test_cases(names: asset_names, declaration: '_ = Image.', app_name: app_name) %>
      }
  }
TEMPLATE
        end
      end
    end
  end
end