require_relative '../objc_template_generator' # frozen_string_literal: true

module Redbreast
  module TemplateGenerator
    module Color
      # Used for creating colors in objective-c.
      class ObjC < TemplateGenerator::ObjC
        include ERB::Util
        def h_template
          <<~TEMPLATE

            #import <UIKit/UIKit.h>

            //THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            <%= generate_category('interface', 'UIColor', app_name) %>
            <%= generate_h_file_objc(asset_names, '+ (UIColor *)', ';')%>
            @end
          TEMPLATE
        end

        def m_template
          <<~TEMPLATE

            #import <UIKit/UIKit.h>

            //THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            <%= generate_category('implementation', 'UIColor', app_name) %>
            <%= generate_m_file_objc(asset_names, '+ (UIColor *)', '\n{\n\treturn [UIColor colorNamed:\@\"', '\" inBundle:', bundle, ' compatibleWithTraitCollection:nil];\n}\n') %>
            @end
          TEMPLATE
        end
      end
    end
  end
end
