require_relative '../objc_template_generator' 

module Redbreast
  module TemplateGenerator
    module Color
      # Used for creating colors in objective-c.
      class ObjC < TemplateGenerator::ObjC
        include ERB::Util
        def h_template
          <<~TEMPLATE

            #import <UIKit/UIKit.h>

            //THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            <%= generate_category('interface', 'UIColor', app_name) %>
            <%= generate_h_file_objc(names: asset_names, variable_declaration: '+ (UIColor *)')%>
            @end
          TEMPLATE
        end

        def m_template
          <<~TEMPLATE

            #import <UIKit/UIKit.h>

            //THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            <%= generate_category('implementation', 'UIColor', app_name) %>
            <%= generate_m_file_objc(names: asset_names, variable_declaration: '+ (UIColor *)', variable_type: '\n{\n\treturn [UIColor colorNamed:\@\"', bundle_name: bundle) %>
            @end
          TEMPLATE
        end
      end
    end
  end
end