require_relative '../swiftui_template_generator' 

module Redbreast
  module TemplateGenerator
    module Color
      # Used for creating colors in swift.
      class SwiftUI < TemplateGenerator::SwiftUI
        include ERB::Util
        def template
          <<~TEMPLATE
            import SwiftUI

            // THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            // swiftlint:disable file_length type_body_length line_length superfluous_disable_command extension_access_modifier
            <%= generate_extension('Color', app_name) %>
            <%= generate_file_swift(names: asset_names, variable: 'public static var %s: Color { Color("%s", bundle: %s) }', bundle: bundle) %>
            }
          TEMPLATE
        end
      end
    end
  end
end
