require_relative '../swift_template_generator'

module Redbreast
    module TemplateGenerator
        module Color
            class Swift < TemplateGenerator::Swift
                include ERB::Util

                def template()
<<-TEMPLATE

import UIKit

//THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
extension UIColor {

    <%- color_names.each do |name| -%>
    static var <%= clean_variable_name(name) %>: UIColor { return UIColor(named: "<%= name %>", in: <%= bundle[:reference] %>, compatibleWith: nil)! }
    <%- end -%>

}

TEMPLATE
                end
            end
        end
    end
end