require_relative '../objc_template_generator'

module Redbreast
  module TemplateGenerator
    module Image
      # Used for creating images in objective-c.
      class ObjC < TemplateGenerator::ObjC
        include ERB::Util
        def h_template
          <<~TEMPLATE

            #import <UIKit/UIKit.h>

            //THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            <%= generate_category('interface', 'UIImage', app_name) %>
            <%= generate_h_file_objc(names: asset_names, variable_declaration: '+ (UIImage *)')%>
            @end
          TEMPLATE
        end

        def m_template
          <<~TEMPLATE

            #import <UIKit/UIKit.h>

            //THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            <%= generate_category('implementation', 'UIImage', app_name) %>
            <%= generate_m_file_objc(names: asset_names, variable_declaration: '+ (UIImage *)', variable_type: '\n{\n\treturn [UIImage imageNamed:\@\"', bundle_name: bundle) %>
            @end
          TEMPLATE
        end
      end
    end
  end
end
