require_relative '../objc_template_generator'

module Redbreast
    module TemplateGenerator
        module Image
            class ObjC < Redbreast::TemplateGenerator::ObjC
                include ERB::Util

                def h_template()
<<-TEMPLATE

#import <UIKit/UIKit.h>

//THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
@interface UIImage (<%= File.basename(bundle[:outputSourcePath]) %>)

<%- image_names.each do |name| -%>
+ (instancetype)<%= clean_variable_name(name) %>;
<%- end -%>

@end

TEMPLATE
                end
                    
                def m_template()
<<-TEMPLATE

#import <UIKit/UIKit.h>

//THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
@implementation UIImage (<%= File.basename(bundle[:outputSourcePath]) %>)

<%- image_names.each do |name| -%>
+(instancetype)<%= clean_variable_name(name) %>
{
    [UIImage imageNamed:@"<%= name %>" inBundle:<%= bundle[:reference] %> compatibleWithTraitCollection:nil];
}
<%- end -%>

@end

TEMPLATE
                end

            end
        end
    end
  end