require_relative '../swift_template_generator' 

module Redbreast
  module TemplateGenerator
    module Image
      # Used for creating images in swift.
      class Swift < TemplateGenerator::Swift
        include ERB::Util

        def template
          <<~TEMPLATE
            import UIKit

            //THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
            <%= generate_extension('UIImage', app_name) %>
            <%= generate_file_swift(names: asset_names, type: ': UIImage { return UIImage(named: "', bundle: bundle) %>
            }
          TEMPLATE
        end
      end
    end
  end
end