require_relative '../swift_template_generator'

module Redbreast
    module TemplateGenerator
        module Image
            class Swift < TemplateGenerator::Swift
                include ERB::Util

                def template()
<<-TEMPLATE
import UIKit

//THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
<%= generate_extension('UIImage', app_name) %>
<%= generate_file_swift(image_names, "\t", "", 'static var ', ': UIImage { return UIImage(named: "', '")! }') %>    
}
TEMPLATE
                end
            end
        end
    end
end