#!/usr/bin/env ruby

require 'rubygems'
require 'commander'
require 'commander/import'
require 'redbreast'

program :name, 'redbreast'
program :version, Redbreast::VERSION
program :description, 'An iOS client for safe and strong resources.'

command :init do |c|
  c.syntax = 'redbreast init'
  c.description = 'Sets up a redbreast.yml config for selected project.'
  c.action do
    Redbreast::ErrorHandler.rescuable do
      Redbreast::Command::Setup.init
    end
  end
end

command :generate do |c|
  c.syntax = 'redbreast generate'
  c.description = 'Generate images and colors strong reference files.'
  c.action do
    Redbreast::ErrorHandler.rescuable do
      Redbreast::Command::ColorGenerator.init
      Redbreast::Command::ImageGenerator.init
      Redbreast::Command::ColorTestGenerator.init
      Redbreast::Command::ImageTestGenerator.init
    end
  end
end

command :install do |c|
  c.syntax = 'redbreast install'
  c.description = 'Sets up file generator in your xcproject build phases. Whenewer you run a buld, new image/color names will be created'
  c.action do
    Redbreast::ErrorHandler.rescuable do
      Redbreast::Command::ConfigurationInstaller.init
    end
  end
end
