require_relative 'images_serializer'

module Redbreast
  module Serializer
    module Image
      class Swift < Base
        include Helper::General

        def save(output_source_path)
          directory = File.dirname(output_source_path)
          FileUtils.mkdir_p directory unless File.exist? directory
          File.write(output_source_path, render)
        end

        def template()
<<-TEMPLATE

import UIKit

//THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
extension UIImage {

    <%- image_names.each do |name| -%>
    static var <%= clean_variable_name(name) %>: UIImage { return UIImage(named: "<%= name %>", in: <%= bundle_reference %>, compatibleWith: nil)! }
    <%- end -%>

}

TEMPLATE
        end
      end
    end
  end
end
